name: manjam_asmaa
description: "منجم الاسماء"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^10.8.0
  flutter_screenutil: ^5.9.3
  sqflite: ^2.4.1
  share_plus: ^10.1.4
  path_provider: ^2.1.5
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_colorpicker: ^1.1.0
  fluttertoast: ^8.2.10
  firebase_core: 3.13.0
  firebase_messaging: ^15.2.5
  cloud_firestore: ^5.6.6
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.8
  sizer: ^2.0.15
  screenshot: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/database/
    - assets/fonts/
    - assets/images/


  fonts:
    - family: HekayaFont
      fonts:
        - asset: assets/fonts/Hekaya_font.otf
    - family: ZainRegular
      fonts:
        - asset: assets/fonts/Zain_Regular_font.ttf
    - family: BIXIE_Regular
      fonts:
        - asset: assets/fonts/BIXIE_Regular.ttf
